default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: quiz_development

test:
  <<: *default
  database: quiz_test

production:
  <<: *default
  database: quiz_production
