# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba99452949536828bd55a48420b6d3f4e16f65098a7441f2fa622c8ba88d34d00341c9dd8aed15521fa5d8593c5ab8131dbf60d3166b2f8975efdf5a9fc05297

test:
  secret_key_base: 7163f1ebe0b271145c5c9e97b1be519821744447df55c4524bac8ae2368a802d057de877d9a3986f53ddc5fb7c67233198dc9e2d8b8b74bc90f4bc4efce9ad1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
